#!/usr/bin/bash
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

alias cp="cp --interactive"
alias grep="grep --color=auto"
alias ll="ls --almost-all --color=auto --human-readable --format=long --indicator-style=slash --time-style=long-iso"
alias mkdir="mkdir --verbose --parents"
alias mv="mv --interactive"
alias rm="rm --interactive --preserve-root"
alias rsync="rsync --human-readable --progress --recursive --links --perms --times --owner --group"
alias watch="watch --color --differences --interval=1 --precise --exec"

# single quotes are used intentionally, see https://www.shellcheck.net/wiki/SC2139 for more information
alias yt_audio='yt-dlp --config-location ${HOME}/.config/yt-dlp-audio.conf'
