#!/usr/bin/bash
# GNU Affero General Public License v3.0 or later (see COPYING or https://www.gnu.org/licenses/agpl.txt)

# sleeps and creates a countdown with a default duration of 5s
_show_wait_timer() {
    # hide cursor
    tput civis
    local DURATION
    DURATION="${1:-5}"
    echo -n "Waiting: "
    while [ "${DURATION}" -ge 1 ]; do
        tput el
        echo -n "${DURATION}"
        tput cub "${#DURATION}"
        sleep 1
        DURATION=$((DURATION - 1))
    done
    echo ""
    # show cursor
    tput cnorm
}

# extract a lot of stuff
_extract() {
    if [ -f "${1}" ]; then
        # Get file type using the 'file' command
        local FILE_TYPE
        FILE_TYPE="$(file --brief --mime-type "${1}")"
        case "${FILE_TYPE}" in
            application/x-tar)
                tar -xvf "${1}" --directory "$(dirname "${1}")" ;;
            application/gzip)
                tar -xvzf "${1}" --directory "$(dirname "${1}")" ;;
            application/x-bzip2)
                tar -xvjf "${1}" --directory "$(dirname "${1}")" ;;
            application/x-xz)
                tar -xvJf "${1}" --directory "$(dirname "${1}")" ;;
            application/zip)
                unzip "${1}" -d "$(dirname "${1}")" ;;
            application/x-rar)
                unrar x "${1}" "$(dirname "${1}")" ;;
            application/x-7z-compressed)
                7z x "${1}" -o"$(dirname "${1}")" ;;
            *)
                echo "Unsupported file type: ${FILE_TYPE}"
                return 1 ;;
        esac
    else
        echo "${1} is not a valid file"
        return 1
    fi
}

_mkarchive() {
    # check if the input argument is provided
    if [ -z "${1}" ]; then
        echo "Error: Missing argument."
        return 1
    # check if the argument exists
    elif [ ! -e "${1}" ]; then
        echo "Error: '${1}' does not exist."
        return 1
    fi

    tar --create --gzip --file="$(basename "${1}")".tar.gz "${1}"
}

# get public ip info using Mullvad's API
_public_ip_info() {
    curl --silent https://am.i.mullvad.net/json | jq
}

# extract rpm contents into current directory
_rpm_extract() {
    rpm2cpio "${1}" | cpio --extract --make-directories --unconditional --preserve-modification-time
}

# removes all containers and images
_podman_rma() {
    podman stop --all --time 2 --ignore
    buildah rm --all || true
    buildah rmi --all --force || true
    podman rm --all --force --time 2 --ignore
    podman rmi --all --force --ignore
    podman system prune --all --force || true
    podman system prune --external --force || true
    echo "Volumes were preserved; to remove them execute: 'podman system prune --volumes'"
}

# creates a symlink
_symlink() {
    local SOURCE
    local DESTINATION
    SOURCE="${1}"
    DESTINATION="${2}"

    # check if the destination is a symlink
    if [ -L "${DESTINATION}" ]; then
        # check if the symlink points to the correct source
        CURRENT_FILE=$(readlink "${DESTINATION}")
        if [ "${CURRENT_FILE}" != "${SOURCE}" ]; then
            ln --symbolic --force "${SOURCE}" "${DESTINATION}"
        fi
    else
        # create the symlink if it does not exist
        ln --symbolic --force "${SOURCE}" "${DESTINATION}"
    fi
}


# ================
# legacy functions
# ================
_git_info() {
    if command -v git &>/dev/null && git rev-parse --is-inside-work-tree &>/dev/null; then
        GIT_UNPUSHED_COMMITS="$(git log --branches --not --remotes --oneline 2>/dev/null | wc --lines 2>/dev/null)"
        GIT_STAGED_CHANGES="$(git diff --cached --stat --name-status 2>/dev/null | wc --lines 2>/dev/null)"
        GIT_UNSTAGED_CHANGES="$(git diff --shortstat 2>/dev/null | sed --expression 's/^ *//' 2>/dev/null)"
        GIT_UNTRACKED_FILES="$(git ls-files "$(pwd)" --exclude-standard --other | wc --lines 2>/dev/null)"
        if [[ "${GIT_UNPUSHED_COMMITS}" -gt 0 ]]; then
            echo -e "\n${BRIGHT}${PURPLE}Unpushed Commits: ${GIT_UNPUSHED_COMMITS}${NORMAL}\c"
        elif [[ "${GIT_STAGED_CHANGES}" -gt 0 ]]; then
            echo -e "\n${BRIGHT}${PURPLE}Staged Changes: ${GIT_STAGED_CHANGES}${NORMAL}\c"
        elif [[ -n "${GIT_UNSTAGED_CHANGES}" ]]; then
            echo -e "\n${BRIGHT}${PURPLE}${GIT_UNSTAGED_CHANGES}${NORMAL}\c"
        elif [[ "${GIT_UNTRACKED_FILES}" -gt 0 ]]; then
            echo -e "\n${BRIGHT}${PURPLE}${GIT_UNTRACKED_FILES} untracked files.${NORMAL}\c"
        else
            echo -e "\n${BRIGHT}${PURPLE}No pending changes.${NORMAL}\c"
        fi
    fi
}
