# GNU Affero General Public License v3.0 or later (see COPYING or https://www.gnu.org/licenses/agpl.txt)

FROM ghcr.io/t-c-l-o-u-d/devcontainer-base-images/arch-linux-devcontainer:latest

# pull in USER from devcontainer.json
ARG USER

# add the USER to the image
RUN useradd --create-home --shell /usr/sbin/bash --groups wheel ${USER}

# =======================================
# repository specific commands start here
# =======================================

# install bash tools
RUN pacman --sync --noconfirm \
    bash-language-server \
    shellcheck \
    shfmt

# =====================================
# repository specific commands end here
# =====================================

# ensure the image starts as USER
USER ${USER}
